# Application Configuration
app:
  name: MyApplication
  environment: development
  debug: true
  log_level: info

# Database Configuration
database:
  host: localhost
  port: 5432
  user: admin
  password: securepassword
  name: mydatabase

# Server Configuration
server:
  host: 0.0.0.0
  port: 8080

# API Keys
api_keys:
  google_maps: your_google_maps_api_key
  stripe: your_stripe_api_key

# Email Settings
email:
  smtp_server: smtp.mailserver.com
  port: 587
  username: no-reply@example.com
  password: emailpassword
  use_tls: true

# Third-Party Services
aws:
  access_key_id: your_aws_access_key
  secret_access_key: your_aws_secret_key
  region: us-east-1

# Feature Flags
features:
  enable_login: true
  enable_signup: false
  enable_analytics: true
